# Cleaning

In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (2.20.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.0.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec[http]<=2024.5.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)

In [3]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

Downloading data:   0%|          | 0.00/231M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

The issue is that `job_posted_date` is currently an object, not a date

In [5]:
df.job_posted_date[0]

'2023-06-16 13:44:15'

In [6]:
type(df.job_posted_date[0])

str

In [7]:
pd.to_datetime(df.job_posted_date)

0        2023-06-16 13:44:15
1        2023-01-14 13:18:07
2        2023-10-10 13:14:55
3        2023-07-04 13:01:41
4        2023-08-07 14:29:36
                 ...
785736   2023-03-13 06:16:16
785737   2023-03-12 06:18:18
785738   2023-03-12 06:32:36
785739   2023-03-12 06:32:15
785740   2023-03-13 06:16:31
Name: job_posted_date, Length: 785741, dtype: datetime64[ns]

This converted it, but left it in its original form in the dataframe

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [9]:
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

It is important that in this case we used the bracket notation when assigning value.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

Now it is datetime

In [12]:
df.job_posted_date.dt.month

0          6
1          1
2         10
3          7
4          8
          ..
785736     3
785737     3
785738     3
785739     3
785740     3
Name: job_posted_date, Length: 785741, dtype: int32

This month value is not saved. We want to add it to our dataframe.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [15]:
df.job_posted_month = df.job_posted_date.dt.month

<ipython-input-15-9bf72d7d3c25>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.job_posted_month = df.job_posted_date.dt.month

In [16]:
df['job_posted_month'] = df.job_posted_date.dt.month

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(2), int32(1), object(11)
memory usage: 89.2+ MB

`job_posted_month` is now a new column in the dataframe

In [19]:
df.sort_values('job_posted_date')

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",1
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,None,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,None,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,None,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,None,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,None,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,NaN,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,None,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,United States,None,NaN,NaN,VirtualVocations,None,None,12

In [20]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,6
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr...",1
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",10
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',...",7
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl...",8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete...",3
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi...",3
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}",3
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh...",3
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}",3

Sorting the data doesn't change its original state if it's done this way.

If we want to we need the `inplace` argument

In [22]:
df.sort_values(by='job_posted_date', inplace=True)
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',...",1
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq...",1
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,None,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud...",1
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,None,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}",1
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,None,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351830,Data Engineer,Data engineer,"San Francisco, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,False,False,Sudan,None,NaN,NaN,JBL Resources,"['azure', 'power bi', 'word']","{'analyst_tools': ['power bi', 'word'], 'cloud...",12
362129,Data Engineer,Data engineer,"Sunnyvale, CA",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:31,True,False,Sudan,None,NaN,NaN,ITCO Solutions,"['sql', 'python', 'java', 'snowflake', 'airflo...","{'cloud': ['snowflake'], 'libraries': ['airflo...",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,NaN,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12
112373,Senior Data Analyst,Marketing Data & Analytics Product Owner - Sen...,"Boston, MA (+1 other)",via Boston Consulting Group,Full-time,False,"New York, United States",2023-12-31 23:59:58,False,False,United States,None,NaN,NaN,Boston Consulting Group,"['sql', 'python', 'r', 'gdpr', 'tableau', 'pow...","{'analyst_tools': ['tableau', 'power bi'], 'li...",12
90102,Machine Learning Engineer,Intelligence analyst,"Boston, MA",via Talent.com,Full-time,False,"New York, United States",2023-12-31 23:59:58,True,False,United States,None,NaN,NaN,VirtualVocations,None,None,12

We want to analyse the yearly salary data. Let's drop

- the hourly column
- the rows without values in `salary_year_avg`

In [26]:
df.drop(labels='salary_hour_avg', axis=1, inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 89.2+ MB

In [28]:
df.dropna(subset=['salary_year_avg'])

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,company_name,job_skills,job_type_skills,job_posted_month
108883,Data Scientist,Data Scientist,"Calabasas, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:02:56,False,True,United States,year,110000.0,PlanetArt,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr...",1
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01 00:06:13,True,False,Argentina,year,65000.0,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",1
365786,Business Analyst,Hospitality Operations Analyst,Anywhere,via Goodwin Recruiting | Job Board,Full-time,True,Georgia,2023-01-01 00:17:55,False,True,United States,year,90000.0,Goodwin Recruiting,"['sql', 'excel', 'powerpoint', 'outlook']","{'analyst_tools': ['excel', 'powerpoint', 'out...",1
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01 00:17:58,False,False,United States,year,55000.0,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea...",1
108099,Data Scientist,Lead Data Scientist (Hybrid),"Burnsville, MN",via Recruit.net,Full-time,False,"Illinois, United States",2023-01-01 00:21:09,False,False,United States,year,120531.0,Apple Valley,"['java', 'sql', 'sql server', 'spring']","{'databases': ['sql server'], 'libraries': ['s...",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186163,Senior Data Scientist,"Tech Lead / Sr Data Scientist, Product Analyti...","Los Angeles, CA",via LinkedIn,Full-time,False,"California, United States",2023-12-31 15:00:46,False,True,United States,year,271526.5,TikTok,"['sql', 'python', 'r', 'express']","{'programming': ['sql', 'python', 'r'], 'webfr...",12
421728,Data Analyst,Data Analyst - Operations,"Los Angeles, CA",via Indeed,Full-time,False,"California, United States",2023-12-31 16:00:07,False,True,United States,year,72750.0,Wilshire Law Firm Plc,"['sql', 'power bi', 'unity']","{'analyst_tools': ['power bi'], 'other': ['uni...",12
313161,Data Scientist,Data Scientist - Security Clearance Required,"Newport News, VA",via IT JobServe,Full-time,False,Georgia,2023-12-31 17:31:57,False,False,United States,year,114062.5,Leidos,"['python', 'r', 'sql', 'pandas', 'numpy']","{'libraries': ['pandas', 'numpy'], 'programmin...",12
336301,Data Scientist,Data scientist,"Dallas, TX",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:22,False,True,Sudan,year,162500.0,Cognizant Technology Solutions,"['python', 'nosql']","{'programming': ['python', 'nosql']}",12
327439,Data Engineer,Staff engineer data,"Southfield, MI",via Talent.com,Full-time,False,Sudan,2023-12-31 23:40:32,False,False,Sudan,year,140000.0,Credit Acceptance,"['express', 'kubernetes']","{'other': ['kubernetes'], 'webframeworks': ['e...",12

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  company_name           785723 non-null  object
 14  job_skills             668704 non-null  object
 15  job_type_skills        668704 non-null  object
 16  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 89.2+ MB

In [30]:
df.dropna(subset=['salary_year_avg'], inplace=True)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22003 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  object
 1   job_title              22003 non-null  object
 2   job_location           21723 non-null  object
 3   job_via                22003 non-null  object
 4   job_schedule_type      21987 non-null  object
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  object
 7   job_posted_date        22003 non-null  datetime64[ns]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  object
 11  salary_rate            22003 non-null  object
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  object
 14  job_skills             20170 non-null  object
 15  job_type_skills        20170 non-null  object
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[ns](1), float64(1), int32(1), object(11)
memory usage: 2.5+ MB